services:

  redis:
    container_name: redis_searxng
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - plebchat_shared
    volumes:
      - ./volumes/redis_searxng:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest

    networks:
      - plebchat_shared

    ports:
      - "8181:8080" # external port -> internal port - 

    volumes:
      - ./volumes/searxng:/etc/searxng
    environment:
      # - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - SEARXNG_BASE_URL=http://host.docker.internal:8080/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    restart: unless-stopped

# networks:
#   searxng:
#     driver: bridge

networks:
  plebchat_shared:
    external: true
