# cloudflared/config.yml

tunnel: 728cecf5-2f81-4f8e-b11a-dd6fa32d1b65

# Path to cloudflared credentials file
# credentials-file: /etc/cloudflared/728cecf5-2f81-4f8e-b11a-dd6fa32d1b65.json

# Define ingress rules for routing to different services
ingress:
  - hostname: dev.plebby.xyz
    service: http://open-webui:3000

  - hostname: devsearch.plebby.xyz
    service: http://searxng:8181

  # Default rule for any requests that don't match above
  - service: http_status:404
